### ISSUE TITLE
Fix tests that fail at random

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#870] opened 2021-04-30 08:32 UTC
A few tests are failing most probably due to not waiting for things to happen before continuing.
I will keep a list of these here so they can be dealt with

1. [mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_disconnect](https://github.com/Open-MSS/MSS/runs/2473754164?check_suite_focus=true)
2. [mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_login](https://github.com/Open-MSS/dockerhub/runs/2506597272?check_suite_focus=true)

**Comment by joernu76** [comment] 2021-04-30 08:54
I propose to skip the tests until they work reliably.
The failing tests are really confusing for both new and old contributors.

**Comment by joernu76** [comment] 2021-04-30 08:54
See #861 and #624 .

**Comment by Marilyth** [comment] 2021-05-05 14:24
I have a branch set up to spam GitHub testing where I check if small waits cause tests not to fail anymore.
Added 500ms of wait for test_disconnect and test_login. If it works a PR will follow shortly.

**Comment by Marilyth** [comment] 2021-05-07 13:41
Whatever it is, the tests are not failing due to waiting. I will do some more testing and will probably have to skip them afterwards.

**Comment by joernu76** [comment] 2021-05-07 14:15
Pleeease make your PR, maybe skipping the annoying login test. The test situation is currently  untenable. 2/3 runs fail.

**Comment by matrss** [comment] 2024-02-16 12:28
I've ran the test suite 100 times in GitHub Actions in #2213 and all of those runs passed without a problem. This indicates that the issue is no longer reproducible and might have been fixed by one of the many recent changes to the test suite. I'll close this and if the problem comes back we can re-open or create a new issue.

**Closed as completed by matrss** 2024-02-16 12:28 UTC
Labels: bug, tests
