### ISSUE TITLE
Mamba problem on installing mss

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#613] opened 2021-01-04 12:30 UTC
Hey there!

I tried following the instructions for installing MSS in the README, namely:
```
$ conda config --add channels conda-forge
$ conda config --add channels defaults
$ conda create -n mssenv python=3
$ conda activate mssenv
$ conda install mamba
$ mamba install mss
```
Everything works fine until the last step, `mamba install mss`.
I tried doing it on a relatively new Linux system, as well as on Windows 10.
Both receive the following output, and error:
```
Looking for: ['mss']

pkgs/msys2/win-64        [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/msys2/noarch        [====================] (00m:00s) Done
pkgs/r/win-64            [====================] (00m:00s) Done
pkgs/main/win-64         [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/win-64       [====================] (00m:04s) Done
Encountered problems while solving.
Problem: nothing provides basemap 1.0.7 needed by mss-1.2.1-py27_0
```
I guess there is a reason the old instruction was changed, but using `conda install mss` instead seemed to install and work fine.

**Comment by ReimarBauer** [comment] 2021-01-04 13:12
that's interesting. it seems to try to install a py27 version mss-1.2.1-py27 
The reason may an old catalogue. Which version of anaconda was used?

**Comment by Marilyth** [comment] 2021-01-04 15:38
I installed anaconda fresh on both systems today, I checked a few versions which might be relevant:

mamba 0.7.6
conda 4.9.2
anaconda Command line client (version 1.7.2)

Nothing was done with anaconda other than the few lines provided in the installation instructions.
Something, somewhere must be outdated then, I think.

**Comment by ReimarBauer** [comment] 2021-01-04 17:06
reproduced

we have to use for mamba
`conda create -n mssenv python=3.8`

mamba seems not to be able to decrease the python version. And currently we have not a mss build for python=3.9

**Comment by Marilyth** [comment] 2021-01-05 07:09
I can confirm specifying python=3.8 has solved the issue for me.

**Comment by wolfv** [comment] 2021-01-05 11:09
Hi @Marilyth thanks for trying mamba. 

Indeed, the error message is slightly confusing.

The problem is that conda & mamba handle Python in a special way: the minor version is pinned, so that mamba will always keep python 3.9 unless explicitly asked to change the python version.

You can work around this by either specifying `mamba install mss python=3.8`.

The error message comes from the fact that mamba tries all available versions of `mss`, from "top-to-bottom" (mss-..-py38, mss-..-py37, .., mss-..-py27) and then emits the error message for the last package it could not install (because of the pinning of python 3.9 in the environment).

I hope we can further improve the error messaging in such cases.

Is there anything holding back a python 3.9 release for mss?

**Comment by Marilyth** [comment] 2021-01-05 11:26
> Is there anything holding back a python 3.9 release for mss?

I think this is something @ReimarBauer is more qualified to answer than me.

**Comment by ReimarBauer** [comment] 2021-01-05 12:46
Hi @wolfv thanks for helping ;)

In the past a dependency by a used library was not ready for 3.9. I do recheck this currently.  

It looks to me that the "conda install" focuses on the newest package wanted and makes this the major dependency while mamba does this on the pinned python version. 

May be both can be resolved by first doing a fast lookup, checking if there is a match and the newest package can be installed. If there is no match the user can be asked to try with a specified python version, or maybe the user could enable this. 

Currently we usually have on newer python versions also newer package versions. Only if something is not finished we may have on newer python versions some packages missing. I am thinking about whether it is necessary to show a user that there is a newer version that they cannot install with the current setup.

**Comment by ReimarBauer** [comment] 2021-01-08 19:12
We have now a python-3.9 release.  Possibly it occurs again with > py 3.9.

**Closed as completed by ReimarBauer** 2021-01-08 19:12 UTC
