### ISSUE TITLE
Tests freezing

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1102] opened 2021-07-30 12:28 UTC
Consistently at this point the testing images freeze
https://github.com/Open-MSS/dockerhub/runs/3201589516?check_suite_focus=true

**Edit:**
It doesn't happen always. So this issue isn't as pressing as I thought.

**Comment by matrss** [comment] 2024-02-16 12:28
I've ran the test suite 100 times in GitHub Actions in #2213 and all of those runs passed without a problem. This indicates that the issue is no longer reproducible and might have been fixed by one of the many recent changes to the test suite. I'll close this and if the problem comes back we can re-open or create a new issue.

**Closed as completed by matrss** 2024-02-16 12:28 UTC
Labels: bug, tests
