### ISSUE TITLE
msui with multiple users on one linux computer

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1525] opened 2022-08-16 15:16 UTC
msui under LINUX does create a cache directory with the name  /tmp/msui_wms_cache/
Since this is not user-specific, it forbids using msui on the same computer from different users.

**Comment by ReimarBauer** [comment] 2022-08-17 09:57
This is intended. Because you can change the path in your users configuration.
Just set your prefered path by the configuration editor to a different path.

**Comment by ReimarBauer** [comment] 2022-08-17 12:33
The behaviour is documented, so that is not a bug ;)

https://mss.readthedocs.io/en/stable/usage.html?highlight=wms_cache#caching

We can of course try to improve it. 

Using on linux the /tmp dir also has the "nice" effect that the dir can get purged on reboot. All cache files are gone. When a user wants to keep them unlimited the var has to become used.

It is easy to become changed

![config_Editor](https://user-images.githubusercontent.com/278728/185124380-c3daa16b-0843-41a7-bc3c-aaed254409af.png)

**Comment by jgrooss** [comment] 2022-08-17 12:42
![msui_cache_error](https://user-images.githubusercontent.com/32653190/185128624-e38e3e38-4ecd-4946-8440-d11222edde81.png)
It may be possible to have a more suggestive error message. This is what I get now.
Users that are not aware of a cache feature see that something is wrong, but get no clue how to fix it.

**Comment by ReimarBauer** [comment] 2022-08-18 07:21
We should guide the user to the documetation whenever possible. 

Also users who aware of the cache feature can run into this, because they try to share cache files and use a filesystem configuration with this limitation.

We may be can look on the pros/cons of using the .cache folder in the home dir if it exists and is a local (not shared) dir.

**Comment by jgrooss** [comment] 2022-08-22 12:22
I just tried what happens if I change the wms_cache in the menu "File - >configuration" and save the settings.
This completely rewrites the msui_settings.json file with the consequence that many things are lost, like the predefined map settings. Is it a bug or a feature?

**Comment by ReimarBauer** [comment] 2022-08-22 12:39
Please add an example json for this. So I can try to write a test for that behaviour or to reproduce this.

It should only write changes to the json file. 

And it writes only parts which differ from the defaults.

I can answer after seeing the example.

**Comment by jgrooss** [comment] 2022-08-22 13:25
**Original msui_settings.json:**
```
{
    "filepicker_default": "qt",

    "import_plugins": {
        "Text": ["txt", "mslib.plugins.io.text", "load_from_txt"]
    },

    "export_plugins": {
        "Text": ["txt", "mslib.plugins.io.text", "save_to_txt"]

    },

    "locations": {
        "EDMO": [48.08, 11.28],
	"Broomfield": [39.913,-105.139],
	"RKSO": [37.090599,127.03],
	"RKPD": [33.399601,126.711998],
	"RJFK": [31.803400,130.718994],
	"RJFY": [31.36672,130.838805],
	"RJOK": [33.546101,133.669006]
     },


    "predefined_map_sections": {
        "01 ACCLIP": {"CRS": "EPSG:4326",
                    "map": {"llcrnrlon": 95.0, "llcrnrlat": -5.0,
                            "urcrnrlon": 175.0, "urcrnrlat": 55.0}},
        "02 USA": {"CRS": "EPSG:4326",
                    "map": {"llcrnrlon": -130.0, "llcrnrlat": 20.0,
                            "urcrnrlon": -65.0, "urcrnrlat": 52.0}},
        "03 Europe (stereo)": {"CRS": "EPSG:77740010",
                    "map": {"llcrnrlon": -20.0, "llcrnrlat": 35.0,
                             "urcrnrlon": 40.0, "urcrnrlat": 70.0}},
	"04 North Atlantik (stereo)": {"CRS": "EPSG:77740010",
                    "map": {"llcrnrlon": -30.0, "llcrnrlat": 45.0,
		              "urcrnrlon": 60.0, "urcrnrlat": 78.0}},
        "05 global (cyl)": {"CRS": "EPSG:4326",
                    "map": {"llcrnrlon": -180.0, "llcrnrlat": -90.0,
                              "urcrnrlon": 180.0, "urcrnrlat": 90.0}}		 
    },

   "traj_nas_lon_identifier": ["GPS LON", "LONGITUDE"],
   "traj_nas_lat_identifier": ["GPS LAT", "LATITUDE"],
   "traj_nas_p_identifier": ["STATIC PRESSURE"],
   "new_flighttrack_template": ["RKSO","RJOK"],
   "new_flighttrack_flightlevel": 350,
   "default_WMS": [
       "https://forecast.fz-juelich.de/acclip",
       "https://mss.acom.ucar.edu"
   ],
   "default_VSEC_WMS": [
       "https://forecast.fz-juelich.de/acclip",
    "https://mss.acom.ucar.edu"
   ],
   "default_LSEC_WMS": [
       "https://forecast.fz-juelich.de/acclip",
       "https://mss.acom.ucar.edu"
   ],
   "WMS_login": {
       "https://forecast.fz-juelich.de/acclip": ["xxx", "xxx"],
       "https://mss.acom.ucar.edu/": ["xxx", "xxx"]
   },
   "num_interpolation_points": 201,
   "num_labels": 10,
   "wms_cache_max_size_bytes": 200971520,
   "wms_cache_max_age_seconds": 432000,

   "default_MSCOLAB": ["https://forecast.fz-juelich.de"],
   "MSC_login": {
                  "https://forecast.fz-juelich.de" : ["acclip", "Password"]
   },
   "MSCOLAB_category": "acclip",
   "MSCOLAB_mailid": "my email address",
   "MSCOLAB_password": "my password"
   
   
}

```
`
**modified msui_settings.json**
```

{
    "filepicker_default": "qt",
    "predefined_map_sections": {
        "01 ACCLIP": {
            "CRS": "EPSG:4326",
            "map": {
                "llcrnrlon": 95.0,
                "llcrnrlat": -5.0,
                "urcrnrlon": 175.0,
                "urcrnrlat": 55.0,
                "CRS": "EPSG:4326",
                "BBOX_UNITS": "degree",
                "OPERATION_NAME": "new flight track (1)",
                "epsg": "4326"
            }
        },
        "02 USA": {
            "CRS": "EPSG:4326",
            "map": {
                "llcrnrlon": -130.0,
                "llcrnrlat": 20.0,
                "urcrnrlon": -65.0,
                "urcrnrlat": 52.0
            }
        },
        "03 Europe (stereo)": {
            "CRS": "EPSG:77740010",
            "map": {
                "llcrnrlon": -20.0,
                "llcrnrlat": 35.0,
                "urcrnrlon": 40.0,
                "urcrnrlat": 70.0
            }
        },
        "04 North Atlantik (stereo)": {
            "CRS": "EPSG:77740010",
            "map": {
                "llcrnrlon": -30.0,
                "llcrnrlat": 45.0,
                "urcrnrlon": 60.0,
                "urcrnrlat": 78.0
            }
        },
        "05 global (cyl)": {
            "CRS": "EPSG:4326",
            "map": {
                "llcrnrlon": -180.0,
                "llcrnrlat": -90.0,
                "urcrnrlon": 180.0,
                "urcrnrlat": 90.0
            }
        }
    },
    "default_WMS": [
        "https://forecast.fz-juelich.de/acclip",
        "https://mss.acom.ucar.edu"
    ],
    "default_VSEC_WMS": [
        "https://forecast.fz-juelich.de/acclip",
        "https://mss.acom.ucar.edu"
    ],
    "default_LSEC_WMS": [
        "https://forecast.fz-juelich.de/acclip",
        "https://mss.acom.ucar.edu"
    ],
    "default_MSCOLAB": [
        "https://forecast.fz-juelich.de"
    ],
    "MSCOLAB_mailid": "my email address",
    "MSCOLAB_password": "my password",
    "MSCOLAB_category": "acclip",
    "MSC_login": {
        "https://forecast.fz-juelich.de": [
            "acclip",
            "Password"
        ]
    },
    "WMS_login": {
        "https://forecast.fz-juelich.de/acclip": [
            "xxx",
            "xxx"
        ],
        "https://mss.acom.ucar.edu/": [
            "xxx",
            "xxx"
        ]
    },
    "wms_cache": "/tmp/msui_wms_cache_tmp",
    "wms_cache_max_size_bytes": 200971520,
    "locations": {
        "EDMO": [
            48.08,
            11.28
        ],
        "Broomfield": [
            39.913,
            -105.139
        ],
        "RKSO": [
            37.090599,
            127.03
        ],
        "RKPD": [
            33.399601,
            126.711998
        ],
        "RJFK": [
            31.8034,
            130.718994
        ],
        "RJFY": [
            31.36672,
            130.838805
        ],
        "RJOK": [
            33.546101,
            133.669006
        ]
    },
    "new_flighttrack_template": [
        "RKSO",
        "RJOK"
    ],
    "new_flighttrack_flightlevel": 350,
    "export_plugins": {
        "Text": [
            "txt",
            "mslib.plugins.io.text",
            "save_to_txt",
            "qt"
        ]
    },
    "import_plugins": {
        "Text": [
            "txt",
            "mslib.plugins.io.text",
            "load_from_txt",
            "qt"
        ]
    }
}

```

**Comment by jgrooss** [comment] 2022-08-22 13:27
Above are the settings files before and after the saving. The second file does still contain the map section "01 ACCLIP" but it is not displayed by the msui.

**Comment by ReimarBauer** [comment] 2022-08-22 15:01
The 01 entry in your example gets wrong, it should be
```
 "01 ACCLIP": {
            "CRS": "EPSG:4326",
            "map": {
                "llcrnrlon": 95.0,
                "llcrnrlat": -5.0,
                "urcrnrlon": 175.0,
                "urcrnrlat": 55.0
            }
        },
```

When I repeat your example it also looks like this to me.

next is to write a test for this and understand how the data got this additional 
 
```
                "CRS": "EPSG:4326",
                "BBOX_UNITS": "degree",
                "OPERATION_NAME": "new flight track (1)",
                "epsg": "4326"
```

**Comment by jgrooss** [comment] 2022-08-22 15:12
that means it is a bug, that msui does not correctly save the settings file?

**Comment by ReimarBauer** [comment] 2022-08-22 15:15
not sure if it is a bug, I can't reproduce it. But I don't know how you added the extra lines. 

![result](https://user-images.githubusercontent.com/278728/185957139-cc753968-285d-4c14-bb09-0bb92a1c6144.png)

In the configuration editor we can't have other than the 4 entries.

![new_entry](https://user-images.githubusercontent.com/278728/185957309-fa55e04d-746a-46c1-801b-bb8c13e0b78c.png)

**Comment by ReimarBauer** [comment] 2022-08-22 15:20
Could it be that the file was opened in emacs or vim, while you were saving it with msui?

When you now repeat, did you get the same problem shown?

**Comment by ReimarBauer** [comment] 2022-08-22 15:23
I file a new issue, in a moment

**Comment by jgrooss** [comment] 2022-08-22 15:34
with the following steps the error can be reproduced:

1. write first file msui_settings.json to $HOME/.config/msui
2. open msui
3. load an ftml flight path
4. change cache directory under Menue: File/Configuration and save
5. Close and re-open msui

-> The first map entry contains additional useless lines
                "CRS": "EPSG:4326",
                "BBOX_UNITS": "degree",
                "OPERATION_NAME": "new flight track (1)",
                "epsg": "4326"
-> The first map entry is not displayed in the top view selection

(no error if step 3 is removed)

**Comment by ReimarBauer** [comment] 2022-08-22 15:44
I got to the same result
https://github.com/Open-MSS/MSS/issues/1530

**Comment by ReimarBauer** [comment] 2022-08-22 15:46
Because we mixed here more than one "issue" we may be should close this one and add an enhancement for a solution of a better default for a multiuser setup. 
Do you agree? And want to add that new issue?

**Comment by jgrooss** [comment] 2022-08-23 06:52
agreed

**Comment by ReimarBauer** [comment] 2022-09-27 06:20
created a good first issue
https://github.com/Open-MSS/MSS/issues/1567

**Closed as completed by ReimarBauer** 2022-09-27 06:20 UTC
Labels: question
