### ISSUE TITLE
develop: test_wms_control.py can crash 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1972] opened 2023-08-30 19:38 UTC
```
current thread 0x00007f18aa5ef740 (most recent call first):
  File "/__w/MSS/MSS/tests/_test_msui/test_wms_control.py", line 568 in setup_method
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/python.py", line 776 in _call_with_optional_argument
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/python.py", line 896 in xunit_setup_method_fixture
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 895 in call_fixture_func
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 1123 in pytest_fixture_setup
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 1069 in execute
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 693 in _compute_fixture_value
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 607 in _get_active_fixturedef
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 585 in getfixturevalue
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/fixtures.py", line 566 in _fillfixtures
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/python.py", line 1791 in setup
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 494 in setup
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 157 in pytest_runtest_setup
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 341 in from_call
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 127 in runtestprotocol
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/main.py", line 324 in _main
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/_pytest/config/__init__.py", line 189 in console_main
  File "/opt/conda/envs/mss-develop-env/bin/pytest", line 10 in <module>

Extension modules: psutil._psutil_linux, psutil._psutil_posix, _brotli, sip, PyQt5.sip, PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, cftime._cftime, netCDF4._netCDF4, pyproj._compat, pyproj._datadir, pyproj._network, pyproj._geod, pyproj.list, pyproj._crs, pyproj._transformer, pyproj.database, pyproj._sync, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, _geoslib, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.linalg._flinalg, scipy.special._ellip_harm_2, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, markupsafe._speedups, _cffi_backend, greenlet._greenlet, tornado.speedups, __original_module__thread, __original_module_select, __original_module_time, PyQt5.QtTest, shapely.speedups._speedups, lxml._elementpath, lxml.etree, lxml.objectify, zope.interface._zope_interface_coptimizations, multidict._multidict, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda (total: 164)
/__w/_temp/2c9f11a3-f60d-4f99-97db-f910d9796a1f.sh: line 9:   277 Aborted                 (core dumped) pytest -v --durations=20 --reverse --cov=mslib tests
/opt/conda/envs/mss-develop-env/lib/python3.10/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
tests/_test_msui/test_wms_control.py::TestWMSControlWidgetSetupSimple::test_xml_time_error ============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.0, pluggy-1.3.0 -- /opt/conda/envs/mss-develop-env/bin/python3.10
cachedir: .pytest_cache
rootdir: /__w/MSS/MSS
configfile: pytest.ini
plugins: monitor-1.6.5, flake8-1.1.1, xdist-3.3.1, pep8-1.0.6, reverse-1.7.0, cov-4.1.0, timeout-2.1.0
timeout: 60.0s
timeout method: signal
timeout func_only: False
collecting ... collected 530 items / 530 deselected / 1 skipped / 0 selected
run-last-failure: no previously failed tests, deselecting all items.
```

**Comment by matrss** [comment] 2024-02-16 12:27
I've ran the test suite 100 times in GitHub Actions in #2213 and all of those runs passed without a problem. This indicates that the issue is no longer reproducible and might have been fixed by one of the many recent changes to the test suite. I'll close this and if the problem comes back we can re-open or create a new issue.

**Closed as completed by matrss** 2024-02-16 12:27 UTC
Labels: tests
