### ISSUE TITLE
MSUI: Window title is very very long and has redundant information

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1961] opened 2023-08-28 20:04 UTC
Seen under MSUI 8.1.1 under Windows 11 on a MSColab project. See screenshot below

![grafik](https://github.com/Open-MSS/MSS/assets/114411636/615ac8fa-d65a-4d38-9b9a-bef20fb84faa)

**Comment by ReimarBauer** [comment] 2023-08-29 11:06
do you have an idea to reproduce that. had that also once last year?

https://github.com/Open-MSS/MSS/issues/1441

**Comment by joernu76** [comment] 2023-09-01 01:33
Saw that as well, will have a look.

**Comment by joernu76** [comment] 2023-09-01 01:39
Might be fixed on accident by #1962
Cannot reproduce currently, will observe.

**Comment by joernu76** [comment] 2023-09-01 02:54
Happens reproducibly when I import a DLRKML file into an operation.

**Closed as completed** 2023-09-06 19:48 UTC
