### ISSUE TITLE
mscolab login credentials not memorized

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1841] opened 2023-07-27 12:11 UTC
In version 8, the usernames and passwords should not be contained in the msui_settings.json file but are saved on the local computer. However, this does not work for the mscolab login.  
Neither the file msui_settings.json is changed nor the credentials are memorized.

**Comment by ReimarBauer** [comment] 2023-07-27 22:42
Please Check if you can use the keyring of your System. It may need a configuration.
We installed keyring into the env. Try to use the command and set a password. Report what it shows.

**Comment by jgrooss** [comment] 2023-07-28 06:43
which command?

**Comment by ReimarBauer** [comment] 2023-07-28 06:55
keyring

**Comment by jgrooss** [comment] 2023-07-28 06:58
```
(mssenv) icg122@icg1805:$ keyring
usage: keyring [-h] [-p KEYRING_PATH] [-b KEYRING_BACKEND] [--list-backends] [--disable] [--print-completion {bash,zsh,tcsh}] [{get,set,del}] [service] [username]
keyring: error: Specify operation 'get', 'del', or 'set'.
```

**Comment by jgrooss** [comment] 2023-07-28 07:02
It is in mssenv environment and version 8.1.0; should I update to 8.1.1?

**Comment by ReimarBauer** [comment] 2023-07-28 07:04
Always use the newest Version.
You Showed the Syntax of the command. Use it to set a password.

When it needs configurations it tells that

**Comment by ReimarBauer** [comment] 2023-07-28 07:06
https://github.com/Open-MSS/MSS/releases/tag/8.1.1

Your problem may have been fixed already.

**Comment by jgrooss** [comment] 2023-07-28 07:22
1. when updating msui, I get the follwing warning
```
msui --update
WARNING:root:Couldn't import mscolab_settings (ImportError:'No module named 'mscolab_settings''), using dummy config.
```
2. keyring seems to work
```
$ keyring set service j.-u.grooss
Password for 'j.-u.grooss' in 'service': 
```
3. also in 8.1.1 the mscolab username and password are not saved and requested at each login 

4. if the initial msui_config.json contains the line 'MSCOLAB_mailid": "my email adress",' 
this seems to be written into the keyring without replacing with the correct email/password on further login

**Comment by joernu76** [comment] 2023-07-28 07:30
The MSCOLAB_mailid in config should be the correct mail-address.
Otherwise, one needs to replace the wrong with the correct one, but the password should be auto-filled??

**Comment by joernu76** [comment] 2023-07-28 07:31
For me, 8.1.1 worked pretty well with the correct mailid in the config. I am using the develop version now, for other reasons, which causes some issues when switching to 8.1.1, so I cannot test this easily.

**Comment by ReimarBauer** [comment] 2023-07-28 07:42
Maybe close this issue and file one New for the  MSCOLAB_MAILID config var?

**Comment by jgrooss** [comment] 2023-07-28 07:48
ok. understood. That means
1. the line MSCOLAB_mailid needs to be in the config file and correctly filled before calling the msui 
2. then the keyring saves the password and deletes the MSCOLAB lines
changing MSCOLAB_mailid seems also possible later. this is still left in the config file

Something to mention to the users, that they should actively edit the config file.

**Comment by jgrooss** [comment] 2023-07-28 07:48
but this issue can be closed

**Comment by jgrooss** [comment] 2023-07-28 07:51
but maybe it would be more user-friendly if the msui/mscolab also changes the entry for MSCOLAB_mailid?

**Comment by joernu76** [comment] 2023-07-28 08:01
The develop branch is already way more user-friendly IMHO. It certainly is different, but it has one fewer dialogue, so it certainly is simpler.

**Comment by joernu76** [comment] 2023-07-28 08:05
I checked the develop branch. In the develop branch, the mailid in the config-file is updated automatically (on request) after a successful login. The password is either way in the keyring.

But also in stable, the config-file should be updated with a different used mail-id *after* successful login...?

**Comment by ReimarBauer** [comment] 2023-07-28 08:21
I close it now. The Initial ticket is not a Bug in 8.1.1. 

The discussion for the other issue should go into a new issue.

**Closed as completed** 2023-07-28 08:23 UTC
Labels: bug
