### ISSUE TITLE
develop: ERROR collecting gw5, pytest-xdist known limitations problem

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2003] opened 2023-09-06 08:17 UTC
```
To see why this happens see Known limitations in documentation
__________________________________________________________________ ERROR collecting gw5 __________________________________________________________________
Different tests were collected between gw2 and gw5. The difference is:
```

https://pytest-xdist.readthedocs.io/en/latest/known-limitations.html

**Comment by matrss** [comment] 2024-02-16 10:34
I do not see this in the latest actions logs. Is this still reproducible?

**Comment by matrss** [comment] 2024-05-06 09:17
I cannot reproduce the issue and since a lot has changed in the CI setup and test suite this might have been fixed in the meantime. I'll close this and if you see the issue again feel free to re-open (ideally with a link to the CI logs where this happens, to have a chance at reproducing and debugging).

**Closed as completed by matrss** 2024-05-06 09:17 UTC
Labels: question
