### ISSUE TITLE
Starting MSS under Windows opens confusing mamba and/or conda windows

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1145] opened 2021-08-13 06:31 UTC
Now: Starting MSS opens several command windows for mama (and or conda) upon starting on Windows.

These Windows hide the main window and stay open rather long.

The main window is also hidden behind other application

This is very confusing.

Desired state: No windows open for those processes.

**Comment by ReimarBauer** [comment] 2021-08-13 07:49
I tried to reproduce this, On my guacamole windows system it looks like this video shows.

![windows_mss_start](https://user-images.githubusercontent.com/278728/129323301-89dd64f0-81dd-46bb-959c-8bdce3e5eb0c.gif)


Please share more details.

**Comment by ReimarBauer** [comment] 2021-08-13 07:54
Ok I see the difference. When we start it by the desktop or program manager Icon this happens what in the issue is described.

![windows_mss_desktop_app](https://user-images.githubusercontent.com/278728/129324772-75f9c8d7-aaba-4045-a483-345b3513a1b1.gif)

**Comment by joernu76** [comment] 2021-08-13 08:04
Correct, I replicated it with the affected user and the Window-opening/hiding only happens when using the menu entry.
The time between starting MSS and the mainwindow appearing is rather long either way...

**Comment by ReimarBauer** [comment] 2021-08-13 08:09
I tried also on linux from the desktop icon, it starts faster, different cpu etc. 
But I also don't have the windows popping up and covering the screen.

We have to look for MS Windows options.

**Comment by ReimarBauer** [comment] 2021-08-13 11:32
The startup speed has to be addressed in develop, the fix promises this behaviour

![new_behaviour_on_windows](https://user-images.githubusercontent.com/278728/129350978-8e8207e7-c7cc-4269-a6a4-c7ca37b1dbcb.gif)

**Closed as completed** 2021-08-13 15:21 UTC
Labels: bug, minor, msui
