### ISSUE TITLE
tests can have a timeout

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1685] opened 2023-03-05 08:49 UTC
random msui tests reach a timeout 

```
Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
```
I assume we close the application before socketio has read the whole information or we need a bit more time for the connection.

Because of the discussion on https://stackoverflow.com/questions/67913861/python-multiprocessing-weird-behavior-when-not-using-time-sleep 

I try with time.sleep() instead of qwait

**Comment by ReimarBauer** [comment] 2023-03-05 10:59
likly  a duplicate of  #1102

**Comment by ReimarBauer** [comment] 2023-04-01 13:56
this can also be introduced by  a wrong mocking, e.g. mocking PyQt5.QtWidgets.QMessageBox instead of a required yes @mock.patch("PyQt5.QtWidgets.QMessageBox.question", return_value=QtWidgets.QMessageBox.Yes)

**Comment by ReimarBauer** [comment] 2023-04-23 19:38
I often see errors like 
`ERROR tests/_test_msui/test_mscolab.py::Test_Mscolab::test_add_operation - requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=25486): Read timed out. (read timeout=10`)

It could be that another process blocks that port by the root user

`tcp      157      0 localhost:25486         localhost:45670         CLOSE_WAIT  root       0  `

**Comment by matrss** [comment] 2024-02-16 12:28
I've ran the test suite 100 times in GitHub Actions in #2213 and all of those runs passed without a problem. This indicates that the issue is no longer reproducible and might have been fixed by one of the many recent changes to the test suite. I'll close this and if the problem comes back we can re-open or create a new issue.

**Closed as completed by matrss** 2024-02-16 12:28 UTC
Labels: enhancement, tests
