### ISSUE TITLE
python-flake8 max-line-length failure

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2111] opened 2023-12-08 08:15 UTC
The setup.cfg defines a max-line-length = 120 and this is overwritten in the python-flake8 with 127.

The extra definition in the worker script should be removed so that the settings from setup.cfg are used

**Comment by rohit2p** [comment] 2024-01-02 17:38
i want to work on this

**Comment by Ved1512** [comment] 2024-01-03 14:21
I would like to work on this issue.

**Comment by rohit2p** [comment] 2024-01-04 19:49
so i have been working on this so in the setup.cfg defines a max-line-length = 120 and this is overwritten in the python-flake8 with 127. so i removed the --max-line-length=127 option from the python-flake8 file. However, the error is still persisting. and i wanted to ask what this work script is actually referring to the python-flake8 file or some other file like docs/conf.py ??

**Comment by ReimarBauer** [comment] 2024-01-05 07:21
the docs/conf.py is only used for the sphinx documentation.
have a look on https://flake8.pycqa.org/en/latest/user/configuration.html

Which error do you refer too?

**Comment by rohit2p** [comment] 2024-01-06 14:17
E501

**Comment by ReimarBauer** [comment] 2024-01-06 14:50
I can't repoduce, maybe give more details. How do you invoke the command? Or send a PR then we can see what the CI does.

**Comment by matrss** [comment] 2024-01-17 16:12
The PR went into stable only. I think we should get this into develop as well.

**Comment by rohit2p** [comment] 2024-01-17 17:52
ok @matrss  so should i create a follow-up PR targeting the develop branch ?

**Comment by matrss** [comment] 2024-01-17 19:34
Yes. You can then just `cherry-pick` the commit from the other PR.

**Comment by rohit2p** [comment] 2024-01-18 17:50
**after i pushed it i encountered this 2 fails**
![image](https://github.com/Open-MSS/MSS/assets/108990670/72a1ff2f-726f-45c9-8f16-412de46b61a1)

i think i can fix the flake8 problem by making changes in this file 

![image](https://github.com/Open-MSS/MSS/assets/108990670/cb910aea-3c97-4bfb-98d3-ddbe9c754b4f)

but i am a bit not sure about this one 

![image](https://github.com/Open-MSS/MSS/assets/108990670/b574355f-3eab-4076-8b33-5d0d3ad714db)

**Comment by matrss** [comment] 2024-01-18 17:55
> i think i can fix the flake8 problem by making changes in this file

Yes, please.

> but i am a bit not sure about this one

I think this is a by-product of the workflow run being in your repository, instead of in a PR in this repository here. It should go away when you make a PR out of it.

**Comment by rohit2p** [comment] 2024-01-18 18:04
by "It should go away when you make a PR out of it." do you mean that i don't need to do anything. because the workflow run in the context of the PR might behave differently and may not encounter the same issues i am facing when triggering the workflow directly in my repository.

**Comment by rohit2p** [comment] 2024-01-18 19:59
@matrss i think i am confused here. so i think need to make a commit in `\tests\_test_msui\test_mscolab_merge_waypoints.py` so that the flake8 workflow will successfully run. and since i need to push this in develop branch. do i create a new branch from develop then make a PR and after the PR will get merged and then i can cherry-pick this pr to develop and this tym since the error is already fixed the workflow will run smoothly and then this is done. is this what i need to do ??

**Comment by matrss** [comment] 2024-01-18 20:16
> by "It should go away when you make a PR out of it." do you mean that i don't need to do anything. because the workflow run in the context of the PR might behave differently and may not encounter the same issues i am facing when triggering the workflow directly in my repository.

Yes, I think this error is caused by a missing personal access token (PAT) that is assumed to be there if run on the develop branch, but is not there in your fork. The failing step simply does not run if the workflow is triggered for a PR, which is the usual way to go for suggesting changes.

> so i think need to make a commit in `\tests\_test_msui\test_mscolab_merge_waypoints.py` so that the flake8 workflow will successfully run.

Yes.

> do i create a new branch from develop then make a PR and after the PR will get merged and then i can cherry-pick this pr to develop and this tym since the error is already fixed the workflow will run smoothly and then this is done.

What I usually do is this:
1. Create a new branch from the current develop branch, name it anything that makes sense for the planned changes
2. Commit the changes to this new branch; in this case you can cherry-pick from the PR that went into stable and fix the other flake8 issue that comes up
3. Push this branch to your fork of the MSS repository
4. Open a PR from this feature branch into the develop branch of the Open-MSS/MSS repository

You don't have to touch the develop branch on your fork at all.

**Comment by rohit2p** [comment] 2024-01-19 19:45
does everything looks fine in this PR @matrss  ?

**Closed as completed** 2024-01-24 07:43 UTC
Labels: bug, good first issue
